/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.FileSystems;
import java.nio.file.Path;

import static linter.Linter.jsLinter;
import static org.junit.Assert.*;

public class LinterTest {
    @Test public void testJSLinter() throws IOException {
        Path path = FileSystems.getDefault().getPath("src/main/resources", "gates.js");
        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setErr(new PrintStream(outContent));

        jsLinter(path);

        assertEquals("Line 3: Missing semicolon.\n" +
                "Line 5: Missing semicolon.\n" +
                "Line 10: Missing semicolon.\n" +
                "Line 11: Missing semicolon.\n" +
                "Line 12: Missing semicolon.\n" +
                "Line 13: Missing semicolon.\n" +
                "Line 14: Missing semicolon.\n" +
                "Line 15: Missing semicolon.\n" +
                "Line 19: Missing semicolon.\n" +
                "Line 25: Missing semicolon.\n" +
                "Line 26: Missing semicolon.\n" +
                "Line 27: Missing semicolon.\n" +
                "Line 28: Missing semicolon.\n" +
                "Line 32: Missing semicolon.\n" +
                "Line 36: Missing semicolon.\n" +
                "Line 40: Missing semicolon.\n" +
                "Line 41: Missing semicolon.\n" +
                "Line 50: Missing semicolon.\n" +
                "Line 51: Missing semicolon.\n" +
                "Line 64: Missing semicolon.\n" +
                "Line 70: Missing semicolon.\n" +
                "Line 71: Missing semicolon.\n" +
                "Line 72: Missing semicolon.\n" +
                "Line 73: Missing semicolon.\n" +
                "Line 74: Missing semicolon.\n" +
                "Line 76: Missing semicolon.\n" +
                "Line 77: Missing semicolon.\n" +
                "Line 78: Missing semicolon.\n" +
                "Line 79: Missing semicolon.\n" +
                "Line 80: Missing semicolon.\n" +
                "Line 82: Missing semicolon.\n" +
                "Line 83: Missing semicolon.\n" +
                "Line 84: Missing semicolon.\n" +
                "Line 85: Missing semicolon.\n" +
                "Line 86: Missing semicolon.\n" +
                "Line 88: Missing semicolon.\n" +
                "Line 89: Missing semicolon.\n" +
                "Line 90: Missing semicolon.\n" +
                "Line 91: Missing semicolon.\n" +
                "Line 92: Missing semicolon.\n" +
                "Line 94: Missing semicolon.\n" +
                "Line 95: Missing semicolon.\n" +
                "Line 96: Missing semicolon.\n" +
                "Line 97: Missing semicolon.\n" +
                "Line 98: Missing semicolon.\n" +
                "Line 99: Missing semicolon.\n" +
                "Line 100: Missing semicolon.\n" +
                "Line 101: Missing semicolon.\n", outContent.toString());
    }
}
