/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class LinterTest {
    @Test public void testJSLinter() {

    }
}
