/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import static basiclibrary.Library.*;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testRollDice(){

        int[] res = roll(10);
        assertTrue("Roll Dice : ", res.length == 10);
    }

    @Test
    public void testContainsDups(){
        int[] arr = {1,2,3,3,4,5,6};
        assertTrue("contains Dups : ", containsDuplicates(arr));
    }

    @Test
    public void testDoesNotContainsDups(){
        int[] arr = {1,2,3,4,5,6};
        assertFalse("contains Dups : ", containsDuplicates(arr));
    }

    @Test
    public void testCalculateAvg(){
        int[] arr = {1,2,3,4,5,6};
        double res = calculateAvg(arr);
        assertTrue("Calc Avg: ",res == 3.5);

    }
}
