/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;

import static basiclibrary.Library.*;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test
    public void testRollDice(){

        int[] res = roll(10);
        assertTrue("Roll Dice : ", res.length == 10);
    }

    @Test
    public void testContainsDups(){
        int[] arr = {1,2,3,3,4,5,6};
        assertTrue("contains Dups : ", containsDuplicates(arr));
    }

    @Test
    public void testDoesNotContainsDups(){
        int[] arr = {1,2,3,4,5,6};
        assertFalse("contains Dups : ", containsDuplicates(arr));
    }

    @Test
    public void testCalculateAvg(){
        int[] arr = {1,2,3,4,5,6};
        double res = calculateAvg(arr);
        assertTrue("Calc Avg: ",res == 3.5);

    }

    @Test
    public void testLowestAvg(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},//63
                {57, 65, 65, 70, 72, 65, 51},//63.57
                {55, 54, 60, 53, 59, 57, 61},//57
                {65, 56, 55, 52, 55, 62, 57}//57.43
        };
        double expected = 57.00;

        assertTrue("Lowest Avg :",lowestAvg(weeklyMonthTemperatures) == expected);

    }

    @Test
    public void testAnalyzeWeatherData(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        final ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        analyzeWeatherData(weeklyMonthTemperatures);

        assertEquals("High: 72\n"+
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n\n", outContent.toString());

    }

    @Test
    public void testTally(){
        List<String> stringList = new ArrayList<>();
        stringList.add("Bubbles");
        stringList.add("Blossom");
        stringList.add("Buttercup");
        stringList.add("Bubbles");
        stringList.add("Bubbles");
        stringList.add("Bubbles");
        stringList.add("Blossom");

        String res = tally(stringList);

        assertTrue("Test Tally : ",res == "Bubbles");

    }


}
