/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {

    // Rolling Dice
    // Write a method called roll that accepts an integer n and rolls a six-sided dice n times.
    // The method should return an array containing the values of the rolls.
    public static int[] roll(int n){
        int[] rolls = new int[n];
        for(int i = 0; i < n; i++){
            rolls[i] =  (int)(Math.random() * (6 + 1));
        }
        return rolls;
    }

    // Contains Duplicates
    // Write a method called containsDuplicates that returns true or false depending
    // on whether the array contains duplicate values.
    public static boolean containsDuplicates(int[] arr){

        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr.length; j++) {
                if(arr[i] == arr[j] && i != j) return true;
            }
        }
        return false;
    }

    // Calculating Averages
    // Write a method that accepts an array of integers and calculates and returns
    // the average of all the values in the array.
    public static double calculateAvg(int[] arr){
        double avg;
        double sum = 0;
        for (int val: arr) {
            sum += (double) val;
        }
        avg = sum / arr.length;
        return  avg;
    }

    // Arrays of Arrays
    // Given an array of arrays calculate the average value for each array and return the array with the lowest average.

}
